// Static products (deprecated - use Firestore)
// export const products = [
{
  id: 1,
    cat: "ranks",
      name: "VIP",
        icon: "⭐",
          price: 4.99,
            perks: ["Custom prefix", "VIP commands", "2x rewards"],
              color: "#63b3ed",
                badge: null,
  },
{
  id: 2,
    cat: "ranks",
      name: "VIP+",
        icon: "🌟",
          price: 9.99,
            perks: ["All VIP perks", "Particles", "Fly"],
              color: "#9f7aea",
                badge: "popular",
  },
{
  id: 3,
    cat: "ranks",
      name: "MVP",
        icon: "💎",
          price: 19.99,
            old: 24.99,
              perks: ["All VIP+", "Join message", "5x rewards"],
                color: "#4fd1c5",
                  badge: "sale",
  },
{
  id: 4,
    cat: "keys",
      name: "Epic Key",
        icon: "💫",
          price: 3.99,
            perks: ["Epic rewards", "Cosmetics"],
              color: "#9f7aea",
                badge: "new",
  },
]